# Generated by Django 6.0.3 on 2026-04-22 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dipartimento",
            fields=[
                (
                    "id_dipartimento",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
                ("sede", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Dipartimenti",
                "db_table": "dipartimento",
                "ordering": ["nome"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="CorsoDiLaurea",
            fields=[
                ("id_cdl", models.IntegerField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=150, unique=True)),
                ("classe_di_laurea", models.CharField(max_length=20)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("Triennale", "Triennale"),
                            ("Magistrale", "Magistrale"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "dipartimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corso_di_laurea",
                        to="struttura.dipartimento",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Corsi di laurea",
                "db_table": "corsodilaurea",
                "ordering": ["nome"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Docente",
            fields=[
                ("id_docente", models.IntegerField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=150)),
                ("cognome", models.CharField(max_length=150)),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default=None,
                        max_length=254,
                        null=True,
                        unique=True,
                        verbose_name="Email del docente",
                    ),
                ),
                ("ruolo", models.CharField(max_length=20)),
                (
                    "dipartimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="docenti",
                        to="struttura.dipartimento",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Docenti",
                "db_table": "docente",
                "ordering": ["nome", "cognome"],
                "managed": True,
            },
        ),
    ]
