# Generated by Django 6.0.3 on 2026-04-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dipartimento",
            fields=[
                (
                    "id_dipartimento",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
                ("sede", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Dipartimenti",
                "ordering": ["nome"],
            },
        ),
    ]
