# Generated by Django 6.0.3 on 2026-04-03 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("struttura", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorsoDiLaurea",
            fields=[
                ("id_cdl", models.IntegerField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=150, unique=True)),
                ("classe_di_laurea", models.CharField(max_length=20)),
                ("tipo", models.CharField(max_length=20)),
                (
                    "id_dipartimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="struttura.dipartimento",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "CorsoDiLaurea",
                "ordering": ["nome"],
            },
        ),
    ]
