# Generated by Django 6.0.3 on 2026-04-15 14:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("struttura", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dipartimento",
            options={
                "managed": True,
                "ordering": ["nom"],
                "verbose_name_plural": "Dipartimenti",
            },
        ),
        migrations.RenameField(
            model_name="dipartimento",
            old_name="nome",
            new_name="nom",
        ),
    ]
