# Generated by Django 6.0.3 on 2026-04-15 14:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("struttura", "0002_alter_dipartimento_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dipartimento",
            options={
                "managed": True,
                "ordering": ["nome"],
                "verbose_name_plural": "Dipartimenti",
            },
        ),
        migrations.RenameField(
            model_name="dipartimento",
            old_name="nom",
            new_name="nome",
        ),
    ]
