# Generated by Django 6.0.3 on 2026-04-03 06:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("struttura", "0002_corsodilaurea"),
    ]

    operations = [
        migrations.RenameField(
            model_name="corsodilaurea",
            old_name="id_dipartimento",
            new_name="dipartimento",
        ),
    ]
