# Generated by Django 6.0.3 on 2026-04-07 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("struttura", "0003_rename_id_dipartimento_corsodilaurea_dipartimento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="corsodilaurea",
            name="dipartimento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="corso_di_laurea",
                to="struttura.dipartimento",
            ),
        ),
    ]
