# Generated by Django 6.0.3 on 2026-04-13 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("struttura", "0004_alter_corsodilaurea_dipartimento"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="corsodilaurea",
            options={"ordering": ["nome"], "verbose_name_plural": "Corsi di laurea"},
        ),
        migrations.CreateModel(
            name="Docente",
            fields=[
                ("id_docente", models.IntegerField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=150)),
                ("cognome", models.CharField(max_length=150)),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default=None,
                        max_length=254,
                        null=True,
                        unique=True,
                        verbose_name="Email del docente",
                    ),
                ),
                ("ruolo", models.CharField(max_length=20)),
                (
                    "dipartimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="docenti",
                        to="struttura.dipartimento",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Docenti",
                "ordering": ["nome"],
            },
        ),
    ]
