# Generated by Django 6.0.3 on 2026-04-13 14:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("struttura", "0005_alter_corsodilaurea_options_docente"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="docente",
            options={"ordering": ["nome", "cognome"], "verbose_name_plural": "Docenti"},
        ),
    ]
