# Generated by Django 6.0.3 on 2026-04-22 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("struttura", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnoAccademico",
            fields=[
                (
                    "id_anno_accademico",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("anno_inizio", models.IntegerField()),
                ("anno_fine", models.IntegerField()),
                (
                    "stato",
                    models.CharField(
                        choices=[
                            ("A", "Attivo"),
                            ("C", "Concluso"),
                            ("F", "Futuro"),
                            ("I", "In preparazione"),
                        ],
                        default="A",
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Anni accademici",
                "db_table": "anno_accademico",
                "ordering": ["stato", "anno_inizio"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Corso",
            fields=[
                ("id_corso", models.IntegerField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=150)),
                ("cfu", models.CharField(max_length=10)),
                ("anno_di_corso", models.CharField(max_length=10)),
                ("semestre", models.CharField(max_length=10)),
            ],
            options={
                "verbose_name_plural": "Corsi",
                "db_table": "corso",
                "ordering": ["nome"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Ssd",
            fields=[
                (
                    "codice_ssd",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("descrizione", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "SSD",
                "db_table": "ssd",
                "ordering": ["codice_ssd"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Docenza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titolare", models.BooleanField(default=False)),
                (
                    "id_anno_accademico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="docenze",
                        to="offerta.annoaccademico",
                    ),
                ),
                (
                    "id_corso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="docenze",
                        to="offerta.corso",
                    ),
                ),
                (
                    "id_docente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="docenze",
                        to="struttura.docente",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Docenze",
                "db_table": "docenza",
                "ordering": [
                    "id_docente",
                    "id_corso",
                    "id_anno_accademico",
                    "titolare",
                ],
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="corso",
            name="ssd",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="corsi",
                to="offerta.ssd",
            ),
        ),
    ]
