# Generated by Django 6.0.3 on 2026-04-13 14:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("offerta", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="docenza",
            options={
                "ordering": [
                    "id_docente",
                    "id_corso",
                    "id_anno_accademico",
                    "titolare",
                ],
                "verbose_name_plural": "Docenze",
            },
        ),
    ]
